version: "3.7"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 8080:80
    deploy:
      replicas: 2
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - mynet
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: 10.2.0.1:5000/app:latest
    deploy:
      replicas: 15
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=app.local 
    networks:
      - mynet

networks:
  mynet:
