version: '3.3'
services:
  pg-0:
    image: bitnami/postgresql-repmgr:11
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    # volumes:
    #   - /nfs/pretix/postgres/master:/bitnami/postgresql:rw
    networks:
      - pretixPgNetwork

  pg-1:
    image: bitnami/postgresql-repmgr:11
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    # volumes:
    #   - /nfs/pretix/postgres/slave1:/bitnami/postgresql:rw
    networks:
      - pretixPgNetwork

  pg-2:
    image: bitnami/postgresql-repmgr:11
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
    # volumes:
    #   - /nfs/pretix/postgres/slave2:/bitnami/postgresql:rw
    networks:
      - pretixPgNetwork

  pgpool:
    image: bitnami/pgpool:4
    ports:
      - 7232:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pretixPgNetwork

  redisproxy:
    # image: 10.2.0.1:5000/pretixhaproxy
    build: ./haproxy
    ports:
      - 7279:6379
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - REDIS_HOSTS=redisnode1,redisnode2,redisnode3
    networks:
      - pretixRedisNetwork

  redisnode1:
    image: jayjohnson/redis-haproxy-clusterable
    environment:
      - CLUSTER_NAME=redis-cluster
      - NODE_TYPE=master
      - IP_BIND=0.0.0.0
      - MASTER_REDIS_HOST=redisnode1
      - MASTER_REDIS_PORT=6379
      - REDIS_PORT=6379
      - SENTINEL_PORT=6378
      - SENTINEL_INSTANCES_FOR_QUORUM=2
      - SENTINEL_DOWN_IN_MILLISECONDS=5000
      - SENTINEL_FAILOVER_TIMEOUT=10000
      - NODE_REPLICAS=redisnode1:6379 redisnode2:6379 redisnode3:6379
      - CLUSTERED=0
    networks:
      - pretixRedisNetwork

  redisnode2:
    image: jayjohnson/redis-haproxy-clusterable
    environment:
      - CLUSTER_NAME=redis-cluster
      - NODE_TYPE=node2
      - IP_BIND=0.0.0.0
      - MASTER_REDIS_HOST=redisnode1
      - MASTER_REDIS_PORT=6379
      - REDIS_PORT=6379
      - SENTINEL_PORT=6378
      - SENTINEL_INSTANCES_FOR_QUORUM=2
      - SENTINEL_DOWN_IN_MILLISECONDS=5000
      - SENTINEL_FAILOVER_TIMEOUT=10000
      - NODE_REPLICAS=redisnode1:6379 redisnode2:6379 redisnode3:6379
      - CLUSTERED=0
    networks:
      - pretixRedisNetwork

  redisnode3:
    image: jayjohnson/redis-haproxy-clusterable
    environment:
      - CLUSTER_NAME=redis-cluster
      - NODE_TYPE=node3
      - IP_BIND=0.0.0.0
      - MASTER_REDIS_HOST=redisnode1
      - MASTER_REDIS_PORT=6379
      - REDIS_PORT=6379
      - SENTINEL_PORT=6378
      - SENTINEL_INSTANCES_FOR_QUORUM=2
      - SENTINEL_DOWN_IN_MILLISECONDS=5000
      - SENTINEL_FAILOVER_TIMEOUT=10000
      - NODE_REPLICAS=redisnode1:6379 redisnode2:6379 redisnode3:6379
      - CLUSTERED=0
    networks:
      - pretixRedisNetwork
        
  web:
    image: pretix/standalone:stable
    volumes:
      # - /nfs/pretix/web/pretix:/etc/pretix:rw
      # - /nfs/pretix/web/data:/data:rw
      - ./pretix.cfg:/etc/pretix/pretix.cfg
    ports:
      - 7280:80
    networks:
      - pretixPgNetwork
      - pretixRedisNetwork
    configs:
      - source: pretixConf
        target: /etc/pretix/pretix.cfg
    deploy:
      replicas: 2

configs:
    pretixConf:
        file: ./pretix.cfg

networks:
  pretixPgNetwork:
    # driver: overlay
  pretixRedisNetwork:
    # driver: overlay