version: '3.1'
services:
    postgres:
        image: postgres:11-alpine
        container_name: pretix_database
        restart: always
        environment:
            - POSTGRES_USER=pretix
            - POSTGRES_DB=pretix
            - POSTGRES_PASSWORD=pretix
        volumes:
         - pgData:/var/lib/postgresql/data
    redis:
        image: redis:4-alpine
        container_name: pretix_cache
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - redisData:/usr/local/etc/redis/redis.conf
    web:
        image: pretix/standalone:stable
        container_name: pretix_server
        restart: always
        depends_on:
            - postgres
            - redis
        ports:
            - "8888:80"
        volumes:
            - ./pretix.cfg:/etc/pretix/pretix.cfg

volumes:
    pgData:
        external: false
    redisData:
        external: false