version: '3.3'
services:
    postgres:
        image: postgres:11-alpine
        container_name: pretix_database
        restart: always
        environment:
            - POSTGRES_USER=pretix
            - POSTGRES_DB=pretix
            - POSTGRES_PASSWORD=pretix
        volumes:
            - pretixData:/var/lib/postgresql/data
        ports:
            - "7232:5432"

    redis:
        image: redis:4-alpine
        container_name: pretix_cache
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - pretixData:/usr/local/etc/redis/redis.conf
            - pretixData:/data
        ports:
         - "7279:6379"

    web:
        image: pretix/standalone:stable
        container_name: pretix_server
        restart: always
        depends_on:
            - postgres
            - redis
        volumes:
            - pretixData:/etc/pretix
            - pretixWeb:/data
        configs:
            - source: pretixConf
              target: /etc/pretix/pretix.cfg
        ports:
            - "7280:80"

volumes:
    pretixData:
        external: false
    pretixWeb:
        external: false

configs:
    pretixConf:
        file: ./pretix.cfg