version: '3.3'
services:
  pgmaster:
    image: paunin/postgresql-cluster-pgsql
    environment:
      INITIAL_NODE_TYPE: "master"
      NODE_ID: 1
      NODE_NAME: node1
      CLUSTER_NODE_NETWORK_NAME: pgmaster
      POSTGRES_PASSWORD: pretix
      POSTGRES_USER: pretix
      POSTGRES_DB: pretix
      CLUSTER_NODE_REGISTER_DELAY: 5
      REPLICATION_DAEMON_START_DELAY: 120
      CLUSTER_NAME: pg_cluster
      REPLICATION_DB: replication_db
      REPLICATION_USER: replication_user
      REPLICATION_PASSWORD: replication_pass
    ports:
      - 7231:5432
    volumes:
      - "pretixPgMaster:/var/lib/postgresql/data"
    networks:
      - pretixPgNetwork
 
  pgslave1:
    image: paunin/postgresql-cluster-pgsql
    environment:
      INITIAL_NODE_TYPE: "standby"
      NODE_ID: 2
      NODE_NAME: node2
      REPLICATION_PRIMARY_HOST: pgmaster
      REPLICATION_UPSTREAM_NODE_ID: 1
    ports:
      - 7230:5432
    depends_on:
      - pgmaster
    volumes:
      - "pretixPgSlave1:/var/lib/postgresql/data"
    networks:
      - pretixPgNetwork
    # deploy:
    #   replicas: 3

  pgslave2:
    image: paunin/postgresql-cluster-pgsql
    environment:
      INITIAL_NODE_TYPE: "standby"
      NODE_ID: 3
      NODE_NAME: node3
      REPLICATION_PRIMARY_HOST: pgmaster
      REPLICATION_UPSTREAM_NODE_ID: 1
    ports:
      - 7229:5432
    depends_on:
      - pgmaster
    volumes:
      - "pretixPgSlave2:/var/lib/postgresql/data"
    networks:
      - pretixPgNetwork
    # deploy:
    #   replicas: 3

  pgpool:
    image: paunin/postgresql-cluster-pgpool
    environment:
      PCP_USER: pcp_user
      PCP_PASSWORD: pcp_pass
      PGPOOL_START_DELAY: 120
      WAIT_BACKEND_TIMEOUT: 120
      REPLICATION_USER: replication_user
      REPLICATION_PASSWORD: replication_pass
      SEARCH_PRIMARY_NODE_TIMEOUT: 5
      DB_USERS: pretix:pretix
      BACKENDS: "2:pgmaster:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1::::,1:pgslave2::::"
    ports:
      - 7232:5432
      - 7298:9898
    networks:
      - pretixPgNetwork
      - pretixOut


  
volumes:
  pretixData:
    external: false
  pretixWeb:
    external: false
  pretixPgSlave1:
    external: false
  pretixPgSlave2:
    external: false
  pretixPgMaster:
    external: false

configs:
    pretixConf:
        file: ./pretix.cfg

networks:
  pretixOut:
    # driver: overlay
  pretixPgNetwork:
    # driver: overlay


