#
# Title: Deployment Configuration for Docker in Swarm MOde
# 
# Description: Use this file to deploy on DETI's dedicated infrastructure. This is meant to be deployed in Docker Swarm mode.
#
# Authors: Filipe Pires (85122) and João Alegria (85048)
#

version: '3.3'
services:
  pg-0:
    image: 10.2.0.1:5000/pretixpostgres
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - NAME={{.Task.Name}}
    volumes:
      - /nfs/pretix/postgres/master:/bitnami/postgresql:rw
    networks:
      - pretixPgNetwork
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 7258:9187

  pg-1:
    image: 10.2.0.1:5000/pretixpostgres
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - NAME={{.Task.Name}}
    volumes:
      - /nfs/pretix/postgres/slave1:/bitnami/postgresql:rw
    networks:
      - pretixPgNetwork
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 7257:9187

  pg-2:
    image: 10.2.0.1:5000/pretixpostgres
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
      - NAME={{.Task.Name}}
    volumes:
      - /nfs/pretix/postgres/slave2:/bitnami/postgresql:rw
    networks:
      - pretixPgNetwork
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 7256:9187

  pgpool:
    image: 10.2.0.1:5000/pretixpgpool
    ports:
      - 7232:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - NAME={{.Task.Name}}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
    networks:
      - pretixPgNetwork
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  redisproxy:
    image: 10.2.0.1:5000/pretixredisproxy
    ports:
      - 7279:6379
      - 7255:9101
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - REDIS_HOSTS=redismaster, redisslave
      - NAME={{.Task.Name}}
    networks:
      - pretixRedisNetwork
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  redismaster:
    image: 10.2.0.1:5000/pretixredismaster
    volumes:
      - /nfs/pretix/redis/master:/data:rw
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    environment:
      - NAME={{.Task.Name}}
    networks:
      - pretixRedisNetwork
    ports:
      - 7254:9121

  redisslave:
    image: 10.2.0.1:5000/pretixredisslave
    volumes:
      - /nfs/pretix/redis/slave:/data:rw
    networks:
      - pretixRedisNetwork
    environment:
      - REDIS_MASTER=redismaster
      - NAME={{.Task.Name}}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - 7253:9121

  redissentinel:
    image: 10.2.0.1:5000/pretixredissentinel
    environment:
      - MASTER_NAME=mymaster
      - QUORUM=1
      - MASTER=redismaster
      - NAME={{.Task.Name}}
    volumes:
      - /nfs/pretix/redis/sentinel:/data:rw
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    networks:
      - pretixRedisNetwork
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - 7252:9121
        
  web:
    image: 10.2.0.1:5000/pretixmypretix
    volumes:
      - /nfs/pretix/web/pretix:/etc/pretix:rw
      - /nfs/pretix/web/data:/data:rw
    environment:
      - POSTGRESIP=pgpool
      - REDISIP=redisproxy
      - NAME={{.Task.Name}}
    ports:
      - 7201:80
      - 7251:9121
    networks:
      - pretixOut
      - pretixPgNetwork
      - pretixRedisNetwork
    secrets:
      - source: pretixConf
        target: /etc/pretix/pretix.cfg
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure

  nginx: 
    image: 10.2.0.1:5000/pretixnginx
    secrets:
      - source: pretixNginxConf
        target: /etc/nginx/nginx.conf
    ports:
      - 7200:8080
      - 7250:9913
    networks:
      - pretixOut
    environment:
      - NAME={{.Task.Name}}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.5.0.108:5000"
        tag: "{{.Name}}/{{.ID}}"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

secrets:
  pretixConf:
    file: ./pretix.cfg
  pretixNginxConf:
    file: ./nginx.conf

networks:
  pretixOut:
    driver: overlay
  pretixPgNetwork:
    driver: overlay
  pretixRedisNetwork:
    driver: overlay
