test:  # The module name. You can have as many modules as you want.
    version: 2  # SNMP version to use. Defaults to 2.
                # 1 will use GETNEXT, 2 and 3 use GETBULK.
    max_repetitions: 25  # How many objects to request with GET/GETBULK, defaults to 25.
                         # May need to be reduced for buggy devices.
    retries: 3   # How many times to retry a failed request, defaults to 3.
    timeout: 5s  # Timeout for each individual SNMP request, defaults to 5s.

    auth:
      # Community string is used with SNMP v1 and v2. Defaults to "public".
      community: gicgirs
    walk:
      - 1.3.6.1.2.1.1.3
      - 1.3.6.1.4.1.2021.10.1.3.1
      - 1.3.6.1.4.1.2021.11.9.0
      - 1.3.6.1.4.1.2021.11.10.0
      - 1.3.6.1.4.1.2021.11.11.0
      - 1.3.6.1.4.1.2021.4.5.0
      - 1.3.6.1.4.1.2021.4.6.0
      - 1.3.6.1.4.1.2021.4.11.0
      - 1.3.6.1.4.1.2021.4.15.0
      - 1.3.6.1.4.1.2021.9.1.6.1
      - 1.3.6.1.4.1.2021.9.1.8.1
      - 1.3.6.1.4.1.2021.9.1.7.1
      - 1.3.6.1.4.1.2021.9.1.9.1

    metrics:
      - name: snmp_sysUpTime
        oid: 1.3.6.1.2.1.1.3
        type: gauge
      - name: snmp_cpuLoad
        oid: 1.3.6.1.4.1.2021.10.1.3.1
        type: DisplayString
      - name: snmp_percentageCpuUserTime
        oid: 1.3.6.1.4.1.2021.11.9.0
        type: gauge
      - name: snmp_percentageCpuSystemTime
        oid: 1.3.6.1.4.1.2021.11.10.0
        type: gauge
      - name: snmp_percentageCpuIdleTime
        oid: 1.3.6.1.4.1.2021.11.11.0
        type: gauge
      - name: snmp_totalRam
        oid: 1.3.6.1.4.1.2021.4.5.0
        type: gauge
      - name: snmp_totalRamUsed
        oid: 1.3.6.1.4.1.2021.4.6.0
        type: gauge
      - name: snmp_totalRamFree
        oid: 1.3.6.1.4.1.2021.4.11.0
        type: gauge
      - name: snmp_totalRamCached
        oid: 1.3.6.1.4.1.2021.4.15.0
        type: gauge
      - name: snmp_totalDiskSize
        oid: 1.3.6.1.4.1.2021.9.1.6.1
        type: gauge
      - name: snmp_totalDiskUsed
        oid: 1.3.6.1.4.1.2021.9.1.8.1
        type: gauge
      - name: snmp_totalDiskFree
        oid: 1.3.6.1.4.1.2021.9.1.7.1
        type: gauge
      - name: snmp_percentageDiskUsed
        oid: 1.3.6.1.4.1.2021.9.1.9.1
        type: gauge
        